### ISSUE TITLE
Can't pull in more characters on 'Load More' button click

### ISSUE THREAD

**Issue by Ajwerth** [Ajwerth/mcdb#2]
In the CharactersList component, I'm fetching the api and then using params to change the limit so I can pull in more than just 20 Characters. 

I created a button that should add 20 to the limit variable allowing for 40 characters to be pulled in. The problem I'm having is that since the fetch is in componentDidMount I can't figure out how to re-render it on the button click.

I did some research and found that you should use getDerivedStateFromProps for this, because componentWillRecieveProps is deprecated, but I can't seem to get it to work.

**Comment by freddiemixell** [comment]
incrementLimit = async () => {
    const currentNum = this.state.limit + 20;
    const res = await fetch(`https://gateway.marvel.com:443/v1/public/characters?limit=${currentNum}&apikey=66ef26227cbc5462b13d6310153279e2`);
    const characters = await res.json();
    this.setState(prevState => ({
      limit: prevState.limit + 20,
      characters: characters.data.results,
    }));
  };

This should do the trick

**Comment by Ajwerth** [comment]
That worked Thanks freddie!
